export const POSTS_SUCCESS = 'POSTS_SUCCESS';
export const POSTS_FAILURE = 'POSTS_FAILURE';
export const POSTS_REQUEST = 'POSTS_REQUEST';

export const POST_TITLE_SUCCESS = 'POST_TITLE_SUCCESS';
export const POST_TITLE_FAILURE = 'POST_TITLE_FAILURE';
export const POST_TITLE_REQUEST = 'POST_TITLE_REQUEST';
